import { BlogPost } from './types';

export const gwansangPosts: BlogPost[] = [
  {
    slug: 'intro',
    title: '관상학 입문: 이목구비로 보는 성격·재물·건강운',
    seoTitle: '관상학 입문 | 이목구비로 보는 성격 재물 건강운',
    description: '관상학의 기초부터 이목구비로 성격·재물·건강운을 보는 방법까지 완벽 해설합니다. 관상 보는법을 쉽게 배워보세요.',
    keywords: ['관상학', '관상 보는법', '이목구비 관상', '관상 뜻', '얼굴 관상'],
    publishedAt: '2026-02-22',
    category: 'gwansang',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'jaeul', title: '재물 관상 완벽 정리', category: 'gwansang' },
      { slug: 'ima', title: '관상 이마 완전정복', category: 'gwansang' },
    ],
  },
  {
    slug: 'jaeul',
    title: '재물 관상 완벽 정리: 코·입·귀로 보는 돈복 3요소',
    seoTitle: '재물 관상 완벽 정리 | 코 입 귀로 보는 돈복',
    description: '코·입·귀로 재물복을 보는 관상학적 방법을 완벽 정리합니다. 내 얼굴의 재물 기운을 확인해보세요.',
    keywords: ['재물 관상', '돈복 관상', '코 관상', '귀 관상', '재물운 관상'],
    publishedAt: '2026-02-22',
    category: 'gwansang',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '관상학 입문', category: 'gwansang' },
      { slug: 'ima', title: '관상 이마 완전정복', category: 'gwansang' },
    ],
  },
  {
    slug: 'noonssep',
    title: '눈썹 관상: 눈썹 모양으로 읽는 리더십·형제운·수명',
    seoTitle: '눈썹 관상 완벽 정리 | 눈썹 모양으로 보는 운세',
    description: '눈썹 모양으로 리더십·형제운·수명을 읽는 관상학적 방법을 알아봅니다. 내 눈썹 관상의 의미를 확인해보세요.',
    keywords: ['눈썹 관상', '눈썹 모양 성격', '눈썹 운세', '관상 눈썹', '눈썹 형태'],
    publishedAt: '2026-02-22',
    category: 'gwansang',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '관상학 입문', category: 'gwansang' },
      { slug: 'jagajindan', title: '관상 자가진단', category: 'gwansang' },
    ],
  },
  {
    slug: 'geongang',
    title: '관상과 건강: 얼굴색과 기색으로 보는 건강 신호',
    seoTitle: '관상으로 보는 건강 | 얼굴색 기색으로 건강 확인',
    description: '얼굴색과 기색으로 현재 건강 상태와 건강 신호를 읽는 관상학적 방법을 알아봅니다.',
    keywords: ['관상 건강', '얼굴색 건강', '기색 관상', '얼굴 건강 신호', '관상 건강운'],
    publishedAt: '2026-02-22',
    category: 'gwansang',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '관상학 입문', category: 'gwansang' },
      { slug: 'jagajindan', title: '관상 자가진단', category: 'gwansang' },
    ],
  },
  {
    slug: 'jeom',
    title: '얼굴의 점 관상학: 빼야 할 점 vs 남겨야 할 점',
    seoTitle: '얼굴 점 관상 | 빼야 할 점과 남겨야 할 점 구분법',
    description: '얼굴의 점 위치로 운세를 보는 관상학적 방법을 알아봅니다. 제거해야 할 점과 복점의 차이를 완벽 정리합니다.',
    keywords: ['얼굴 점 관상', '점 위치 운세', '복점', '점 빼기 관상', '얼굴 점 의미'],
    publishedAt: '2026-02-22',
    category: 'gwansang',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '관상학 입문', category: 'gwansang' },
      { slug: 'jagajindan', title: '관상 자가진단', category: 'gwansang' },
    ],
  },
  {
    slug: 'ima',
    title: '관상 이마 완전정복: 이마로 보는 초년운과 부모복',
    seoTitle: '이마 관상 완전정복 | 이마 넓이 형태로 보는 운세',
    description: '이마 넓이와 형태로 초년운과 부모복을 보는 관상학적 방법을 완벽 해설합니다. 내 이마 관상의 의미를 알아보세요.',
    keywords: ['이마 관상', '이마 넓은 관상', '이마 운세', '관상 이마', '초년운 관상'],
    publishedAt: '2026-02-22',
    category: 'gwansang',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '관상학 입문', category: 'gwansang' },
      { slug: 'jaeul', title: '재물 관상 완벽 정리', category: 'gwansang' },
    ],
  },
  {
    slug: 'jagajindan',
    title: '관상 자가진단: 거울 보며 확인하는 나의 5년 후 성공운',
    seoTitle: '관상 자가진단 | 거울로 보는 내 성공운 셀프 체크',
    description: '거울 하나로 내 관상을 직접 진단하는 방법을 알아봅니다. 5년 후 성공운을 관상학으로 예측해보세요.',
    keywords: ['관상 자가진단', '관상 셀프', '관상 보는법 혼자', '관상 성공운', '내 관상'],
    publishedAt: '2026-02-22',
    category: 'gwansang',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '관상학 입문', category: 'gwansang' },
      { slug: 'jaeul', title: '재물 관상 완벽 정리', category: 'gwansang' },
    ],
  },
];
