import { BlogPost } from './types';

export const mbtiPosts: BlogPost[] = [
  {
    slug: 'intro',
    title: 'MBTI 유래: 칼 융의 분석심리학과 동양 철학의 접점',
    seoTitle: 'MBTI 유래와 역사 | 칼 융과 동양 철학의 접점',
    description: 'MBTI의 유래와 역사, 칼 융의 분석심리학과 동양 철학의 놀라운 접점을 알아봅니다. MBTI를 더 깊이 이해해보세요.',
    keywords: ['MBTI 유래', 'MBTI 역사', '칼 융 MBTI', 'MBTI 뜻', 'MBTI 기원'],
    publishedAt: '2026-02-22',
    category: 'mbti',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'saju-five-elements', title: 'MBTI와 사주 오행', category: 'mbti' },
      { slug: 'mbti-compatibility', title: 'MBTI 궁합 완전정복', category: 'mbti' },
    ],
  },
  {
    slug: 'saju-five-elements',
    title: 'MBTI와 사주 오행: 16가지 성격 유형과 오행의 상관관계',
    seoTitle: 'MBTI 사주 오행 관계 분석 | 16유형 오행 매핑',
    description: 'MBTI 16가지 성격 유형과 사주 오행의 상관관계를 분석합니다. 내 MBTI가 어떤 오행과 연결되는지 알아보세요.',
    keywords: ['MBTI 사주', 'MBTI 오행', 'MBTI 명리학', '16유형 오행', 'MBTI 사주 궁합'],
    publishedAt: '2026-02-22',
    category: 'mbti',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: 'MBTI 유래', category: 'mbti' },
      { slug: 'mbti-compatibility', title: 'MBTI 궁합 완전정복', category: 'mbti' },
    ],
  },
  {
    slug: 'mbti-compatibility',
    title: 'MBTI 궁합 완전정복: 최악의 궁합을 오행으로 극복하는 법',
    seoTitle: 'MBTI 궁합 완전정복 | 상극 궁합 사주로 극복하기',
    description: 'MBTI 궁합을 완벽 분석하고 최악의 궁합도 사주 오행으로 극복하는 방법을 알아봅니다. 16유형 궁합표 포함.',
    keywords: ['MBTI 궁합', 'MBTI 궁합표', 'MBTI 잘 맞는 유형', 'MBTI 최악 궁합', 'MBTI 연애 궁합'],
    publishedAt: '2026-02-22',
    category: 'mbti',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'saju-five-elements', title: 'MBTI와 사주 오행', category: 'mbti' },
      { slug: 'fortune-improvement', title: 'MBTI E·I 개운법', category: 'mbti' },
    ],
  },
  {
    slug: 'fortune-improvement',
    title: 'MBTI E·I 유형별 개운법: 성격 유형에 맞게 운 여는 법',
    seoTitle: 'MBTI E I 유형별 개운법 | 성격별 운 여는 실전법',
    description: 'MBTI E형과 I형의 성격 특성에 맞는 개운법을 알아봅니다. 내 성격 유형에 맞게 운을 여는 실전 방법을 소개합니다.',
    keywords: ['MBTI 개운법', 'MBTI E형 I형', 'MBTI 운세', 'MBTI 행운', 'MBTI 성격 운'],
    publishedAt: '2026-02-22',
    category: 'mbti',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'mbti-compatibility', title: 'MBTI 궁합 완전정복', category: 'mbti' },
      { slug: 'compatibility-table', title: 'MBTI별 사주 궁합표', category: 'mbti' },
    ],
  },
  {
    slug: 'compatibility-table',
    title: 'MBTI별 사주 궁합표: 16유형과 잘 맞는 일주 완전 정리',
    seoTitle: 'MBTI별 사주 궁합표 | 16유형 잘 맞는 일주 정리',
    description: 'MBTI 16유형과 사주 일주별 궁합을 완벽 정리한 표입니다. 내 MBTI에 가장 잘 맞는 사주 일주를 확인해보세요.',
    keywords: ['MBTI 사주 궁합표', 'MBTI 일주 궁합', 'MBTI 16유형 궁합', 'MBTI 천생연분', 'MBTI 사주'],
    publishedAt: '2026-02-22',
    category: 'mbti',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'mbti-compatibility', title: 'MBTI 궁합 완전정복', category: 'mbti' },
      { slug: 'saju-five-elements', title: 'MBTI와 사주 오행', category: 'mbti' },
    ],
  },
];
