import { BlogPost } from './types';

export const sajuPosts: BlogPost[] = [
  {
    slug: 'intro',
    title: '역학의 기초: 사주팔자란 무엇인가?',
    seoTitle: '사주팔자란 무엇인가? 음양오행의 원리 완벽 해설',
    description: '사주팔자의 기초부터 음양오행의 원리까지 완벽 해설합니다. 명리학의 핵심 개념을 쉽게 이해해보세요.',
    keywords: ['사주팔자', '음양오행', '사주 보는법', '사주 뜻', '명리학'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'iljoo', title: '사주 일주 완전정복', category: 'saju' },
      { slug: 'yongshin', title: '사주 용신 찾기', category: 'saju' },
    ],
  },
  {
    slug: 'eumlyek-yanglyeok',
    title: '음력과 양력: 사주 볼 때 생시를 알아야 하는 이유',
    seoTitle: '사주 음력 양력 차이 완벽 정리 | 생시의 중요성',
    description: '사주를 볼 때 음력과 양력 중 무엇을 써야 할까요? 생시가 왜 중요한지, 정확한 사주 계산법을 알아봅니다.',
    keywords: ['사주 음력 양력', '사주 생시', '사주 계산법', '음력 변환', '사주 보는법'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '사주팔자란 무엇인가?', category: 'saju' },
      { slug: 'iljoo', title: '사주 일주 완전정복', category: 'saju' },
    ],
  },
  {
    slug: 'iljoo',
    title: '사주 일주(日柱) 완전정복',
    seoTitle: '사주 일주 완전정복 | 60 일주 배우자복 보는법',
    description: '사주 일주로 나의 본질과 배우자 복을 읽는 법을 완벽 해설합니다. 60 일주별 특징과 궁합을 알아보세요.',
    keywords: ['사주 일주', '일주 뜻', '60 일주', '배우자 사주', '일간 지지'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'sinsal', title: '사주 신살 총정리', category: 'saju' },
      { slug: 'yongshin', title: '사주 용신 찾기', category: 'saju' },
    ],
  },
  {
    slug: 'sinsal',
    title: '사주 신살 총정리',
    seoTitle: '사주 신살 총정리 | 도화살 역마살 현대적 해석',
    description: '사주 신살의 종류와 현대적 의미를 총정리합니다. 도화살·역마살이 현대 사회에서 장점이 되는 법을 알아보세요.',
    keywords: ['사주 신살', '도화살', '역마살', '사주 살풀이', '신살 종류'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'iljoo', title: '사주 일주 완전정복', category: 'saju' },
      { slug: 'yongshin', title: '사주 용신 찾기', category: 'saju' },
    ],
  },
  {
    slug: 'yongshin',
    title: '사주 용신 찾기: 내 사주에서 가장 필요한 기운',
    seoTitle: '사주 용신 찾는법 완벽 가이드 | 내 용신 확인',
    description: '사주 용신이란 무엇이며 어떻게 찾는지 알아봅니다. 내 사주에서 가장 필요한 기운과 활용법을 완벽 해설합니다.',
    keywords: ['사주 용신', '용신 찾는법', '용신 뜻', '사주 기운', '용신 색깔'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '사주팔자란 무엇인가?', category: 'saju' },
      { slug: 'gongmang', title: '사주 공망', category: 'saju' },
    ],
  },
  {
    slug: 'gongmang',
    title: '사주 공망(空亡): 비어있는 운의 의미와 실전법',
    seoTitle: '사주 공망이란? 공망 뜻과 공망 채우는 실전법',
    description: '사주 공망의 의미와 공망이 있는 사람들의 특징을 알아봅니다. 공망을 채우는 실전 개운법도 함께 소개합니다.',
    keywords: ['사주 공망', '공망 뜻', '공망 보는법', '사주 공망 직업', '공망 궁합'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'yongshin', title: '사주 용신 찾기', category: 'saju' },
      { slug: 'sinsal', title: '사주 신살 총정리', category: 'saju' },
    ],
  },
  {
    slug: 'gwanseong',
    title: '사주 관성(官星)으로 보는 직업운',
    seoTitle: '사주 관성으로 보는 직업운 | 내게 맞는 직종 찾기',
    description: '사주 관성으로 직업운과 직장 운세를 보는 법을 알아봅니다. 내 사주에 맞는 직종과 커리어 방향을 찾아보세요.',
    keywords: ['사주 관성', '사주 직업운', '사주 직업', '정관 편관', '사주 진로'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '사주팔자란 무엇인가?', category: 'saju' },
      { slug: 'yongshin', title: '사주 용신 찾기', category: 'saju' },
    ],
  },
  {
    slug: 'ddibyeol-2025',
    title: '띠별 2025년 운세: 사주 오행으로 보는 12띠',
    seoTitle: '2025년 띠별 운세 완벽 정리 | 사주 오행으로 보는 올해',
    description: '2025년 띠별 운세를 사주 오행으로 분석합니다. 12띠별 올해의 흐름과 주의사항, 개운법을 알아보세요.',
    keywords: ['2025년 띠별 운세', '2025 운세', '띠별 운세', '올해 운세', '12띠 운세'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '사주팔자란 무엇인가?', category: 'saju' },
      { slug: 'yongshin', title: '사주 용신 찾기', category: 'saju' },
    ],
  },
  {
    slug: 'unmyeong-byeonhwa',
    title: '운명의 변화: 사주는 정해져 있지만 운명은 바꿀 수 있는가?',
    seoTitle: '사주팔자 운명 바꾸는법 | 운명 변화 가능성',
    description: '사주팔자는 정해진 운명인가, 아니면 바꿀 수 있는가? 명리학의 관점에서 운명 변화의 가능성을 탐구합니다.',
    keywords: ['사주 운명', '운명 바꾸기', '사주팔자 운명', '개운법', '사주 자유의지'],
    publishedAt: '2026-02-22',
    category: 'saju',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '사주팔자란 무엇인가?', category: 'saju' },
      { slug: 'yongshin', title: '사주 용신 찾기', category: 'saju' },
    ],
  },
];
