import { BlogPost } from './types';

export const seongmyeongPosts: BlogPost[] = [
  {
    slug: 'intro',
    title: '성명학 비기: 이름의 한자 획수가 인생에 미치는 영향',
    seoTitle: '성명학이란? 이름 획수가 인생에 미치는 영향 완벽 해설',
    description: '성명학의 기초부터 이름 한자 획수가 운명에 미치는 영향까지 완벽 해설합니다. 내 이름의 기운을 확인해보세요.',
    keywords: ['성명학', '이름 획수', '작명', '성명학 보는법', '이름 운세'],
    publishedAt: '2026-02-22',
    category: 'seongmyeong',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'hoeksu', title: '이름 획수 완벽 정리', category: 'seongmyeong' },
      { slug: 'orhaeng', title: '이름 오행', category: 'seongmyeong' },
    ],
  },
  {
    slug: 'jakseong',
    title: '작명의 기술: 태어난 계절에 부족한 기운을 이름으로 채우기',
    seoTitle: '작명의 기술 | 사주 오행으로 이름 짓는 방법',
    description: '사주에서 부족한 오행 기운을 이름으로 채우는 작명의 기술을 알아봅니다. 좋은 이름 짓는 핵심 원칙을 소개합니다.',
    keywords: ['작명', '이름 짓기', '작명 기준', '사주 작명', '좋은 이름'],
    publishedAt: '2026-02-22',
    category: 'seongmyeong',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '성명학 비기', category: 'seongmyeong' },
      { slug: 'suri-81su', title: '수리 81수 핵심 정리', category: 'seongmyeong' },
    ],
  },
  {
    slug: 'orhaeng',
    title: '이름 오행: 초성으로 보는 소리 오행의 상생·상극',
    seoTitle: '이름 소리 오행 완벽 정리 | 초성으로 보는 오행',
    description: '이름의 초성으로 소리 오행을 분석하는 방법과 상생·상극 관계를 완벽 정리합니다. 내 이름의 오행 기운을 확인해보세요.',
    keywords: ['이름 오행', '소리오행', '성명학 오행', '이름 초성', '오행 상생 상극'],
    publishedAt: '2026-02-22',
    category: 'seongmyeong',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '성명학 비기', category: 'seongmyeong' },
      { slug: 'hoeksu', title: '이름 획수 완벽 정리', category: 'seongmyeong' },
    ],
  },
  {
    slug: 'gaemyeong',
    title: '개명 가이드: 개명 시 반드시 체크해야 할 수리 길흉표',
    seoTitle: '개명 가이드 | 개명 절차와 성명학 수리 길흉 체크법',
    description: '개명을 고민할 때 확인해야 할 성명학 수리 길흉표와 개명 절차를 안내합니다. 좋은 이름으로 바꾸는 완벽 가이드입니다.',
    keywords: ['개명', '개명 방법', '개명 비용', '이름 바꾸기', '개명 효과'],
    publishedAt: '2026-02-22',
    category: 'seongmyeong',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'suri-81su', title: '수리 81수 핵심 정리', category: 'seongmyeong' },
      { slug: 'intro', title: '성명학 비기', category: 'seongmyeong' },
    ],
  },
  {
    slug: 'janyeo-jakseong',
    title: '자녀 작명 완벽 가이드: 사주 오행과 성명학을 동시에 만족하는 이름',
    seoTitle: '자녀 작명 완벽 가이드 | 사주 오행 성명학 이름 짓기',
    description: '아이의 사주 오행과 성명학을 동시에 만족하는 자녀 작명 완벽 가이드입니다. 좋은 이름 짓는 단계별 방법을 알아보세요.',
    keywords: ['자녀 작명', '아기 이름 짓기', '신생아 작명', '사주 작명', '좋은 이름 짓기'],
    publishedAt: '2026-02-22',
    category: 'seongmyeong',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'jakseong', title: '작명의 기술', category: 'seongmyeong' },
      { slug: 'orhaeng', title: '이름 오행', category: 'seongmyeong' },
    ],
  },
  {
    slug: 'suri-81su',
    title: '성명학 수리 81수 핵심 정리',
    seoTitle: '성명학 수리 81수 완벽 정리 | 좋은 획수 나쁜 획수',
    description: '성명학 수리 81수의 핵심을 정리합니다. 좋은 획수 조합과 피해야 할 조합, 각 수리의 의미를 한눈에 알아보세요.',
    keywords: ['수리 81수', '성명학 획수', '이름 획수 길흉', '81수리 표', '성명학 수리'],
    publishedAt: '2026-02-22',
    category: 'seongmyeong',
    contentKo: '',
    contentEn: '',
    toc: [],
    faq: [],
    relatedPosts: [
      { slug: 'intro', title: '성명학 비기', category: 'seongmyeong' },
      { slug: 'gaemyeong', title: '개명 가이드', category: 'seongmyeong' },
    ],
  },
];
